FROM _DOCKER_BASE_

COPY src/agent/kubernetes-agent/requirements.txt /
RUN pip install -r /requirements.txt
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && \
    mv kubectl /usr/local/bin/kubectl

COPY src/agent/kubernetes-agent/src /app

WORKDIR /app

ENV KUBECONFIG /app/.kube/config
ENV PYTHONPATH /app:/usr/local/lib/python3.6:/usr/local/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/site-packages

CMD python main.py
