---
- name: Set starting port
  set_fact:
    initial_port: 2222

- name: Add provisioning host group
  add_host:
    ansible_host: "{{ auth.auth_url }}"
    ansible_port: 22
    ansible_ssh_user: "{{ auth.username }}"
    ansible_ssh_pass: "{{ auth.password }}"
    sshport: "{{ initial_port | int + item | int }}"
    name: "{{ cluster.name_prefix }}{{ item }}"
    groups: "prohosts"
  with_sequence: count={{ cluster.stack_size }} format=%03x

- name: Add netprocessing host group
  add_host:
    ansible_host: "{{ auth.auth_url }}"
    ansible_port: "{{ initial_port | int + item | int }}"
    ansible_ssh_user: "{{ cluster.ssh_user }}"
    ansible_ssh_pass: "{{ cluster.ssh_pass }}"
    name: "AA_{{ cluster.name_prefix }}{{ item }}"
    groups: "nathosts"
  with_sequence: count={{ cluster.stack_size }} format=%03x
  when: mode == "apply"