FROM hyperledger/cello-baseimage:latest

COPY src /app
RUN	cd /app/ && \
	pip install -r requirements.txt && \
	rm -rf /tmp/cello

CMD bash /app/celery.sh && if [ "$DEBUG" = "True" ]; then python dashboard.py ; else gunicorn -w 1 --worker-class eventlet -b 0.0.0.0:8080 dashboard:app ;fi
