# Copyright IBM Corp, All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM node:8.11.3
MAINTAINER h3c "@h3c.com"

COPY user-dashboard/src /var/www
RUN cd /var/www && yarn install && npm run build
RUN cd /var/www/packages/fabric-1.4 && npm install
WORKDIR /var/www
EXPOSE 8081
COPY fabric-tools/  /opt/fabric_tools/
COPY jq-linux64 /usr/bin/jq
RUN chmod +x /usr/bin/jq
ENV FABRIC_VERSION 1.0.5
RUN cp /opt/fabric_tools/v1_4/configtxgen /usr/local/bin/configtxgen
COPY user-dashboard/fabric/fabric /etc/hyperledger/fabric
ENV MONGO_PORT 27017
COPY start.sh /root/start.sh
RUN chmod +x /root/start.sh

CMD ["/bin/bash","/root/start.sh"]
